export const metodoPago = [
    {"label": "contado"}, {"label": "credito"}
]

export const categories = [
  "Electrónica",
  "Telefonía móvil",
  "Computadoras y laptops",
  "Tablets",
  "Televisores",
  "Audio y sonido",
  "Auriculares",
  "Parlantes Bluetooth",
  "Cámaras digitales",
  "Drones",
  "Smartwatches",
  "Accesorios de celular",
  "Accesorios de computadora",
  "Componentes de PC",
  "Impresoras",
  "Toners y cartuchos",
  "Consolas de videojuegos",
  "Videojuegos",
  "Controles y mandos",
  "Electrodomésticos",
  "Heladeras",
  "Freezers",
  "Microondas",
  "Hornos eléctricos",
  "Cocinas",
  "Aspiradoras",
  "Licuadoras",
  "Batidoras",
  "Procesadoras de alimentos",
  "Cafeteras",
  "Tostadoras",
  "Planchas",
  "Ventiladores",
  "Aires acondicionados",
  "Calefactores",
  "Purificadores de aire",
  "Hogar",
  "Decoración",
  "Muebles de sala",
  "Muebles de comedor",
  "Muebles de dormitorio",
  "Colchones",
  "Almohadas",
  "Ropa de cama",
  "Cortinas",
  "Iluminación interior",
  "Alfombras",
  "Baño",
  "Cocina",
  "Menaje del hogar",
  "Utensilios de cocina",
  "Cubiertos",
  "Platos y vajilla",
  "Cristalería",
  "Cacerolas y ollas",
  "Sartenes",
  "Cuchillos de cocina",
  "Organización del hogar",
  "Limpieza",
  "Escobas y mopas",
  "Detergentes",
  "Ambientadores",
  "Productos ecológicos",
  "Jardinería",
  "Plantas y macetas",
  "Herramientas de jardinería",
  "Sillas de jardín",
  "Parrillas",
  "Gazebos",
  "Piscinas",
  "Moda",
  "Ropa masculina",
  "Ropa femenina",
  "Ropa infantil",
  "Ropa deportiva",
  "Ropa interior",
  "Calzado",
  "Zapatos formales",
  "Zapatillas deportivas",
  "Botas",
  "Sandalias",
  "Carteras",
  "Mochilas",
  "Accesorios de moda",
  "Relojes",
  "Gafas de sol",
  "Sombreros",
  "Bufandas",
  "Joyas",
  "Anillos",
  "Collares",
  "Pulseras",
  "Aros",
  "Bisutería",
  "Belleza",
  "Perfumes",
  "Maquillaje",
  "Cremas faciales",
  "Shampoo",
  "Acondicionador",
  "Tratamientos capilares",
  "Depilación",
  "Manicure y pedicure",
  "Cepillos y peines",
  "Equipos de estética",
  "Salud",
  "Medicamentos",
  "Vitaminas y suplementos",
  "Equipos médicos",
  "Termómetros",
  "Tensiómetros",
  "Botiquines",
  "Ortopedia",
  "Productos naturales",
  "Cuidado personal",
  "Higiene bucal",
  "Cepillos dentales",
  "Pastas dentales",
  "Enjuagues bucales",
  "Cuidado íntimo",
  "Toallas femeninas",
  "Cuidado corporal",
  "Jabones",
  "Desodorantes",
  "Lociones",
  "Protector solar",
  "Deportes",
  "Fitness",
  "Pesas",
  "Cintas de correr",
  "Bicicletas",
  "Ropa deportiva",
  "Calzado deportivo",
  "Accesorios de gimnasio",
  "Pelotas",
  "Raquetas",
  "Guantes deportivos",
  "Camping",
  "Carpas",
  "Bolsas de dormir",
  "Colchonetas",
  "Camping y aventura",
  "Pesca",
  "Caza",
  "Deportes acuáticos",
  "Surf",
  "Natación",
  "Buceo",
  "Kayak",
  "Deportes de invierno",
  "Snowboard",
  "Esquí",
  "Patinaje",
  "Bicicletas y accesorios",
  "Repuestos de bicicleta",
  "Cascos",
  "Protecciones",
  "Herramientas de bici",
  "Infantil",
  "Juguetes",
  "Muñecas",
  "Autos a control remoto",
  "Bloques de construcción",
  "Peluches",
  "Juegos de mesa",
  "Puzzles",
  "Libros infantiles",
  "Bebés",
  "Pañales",
  "Mamaderas",
  "Chupetes",
  "Sillas para auto",
  "Cochecitos",
  "Cunas",
  "Ropa para bebé",
  "Artículos escolares",
  "Útiles escolares",
  "Mochilas escolares",
  "Lápices y bolígrafos",
  "Cuadernos",
  "Cartucheras",
  "Papelería",
  "Oficina",
  "Sillas de oficina",
  "Escritorios",
  "Computadoras de oficina",
  "Monitores",
  "Teclados y mouse",
  "Impresoras de oficina",
  "Suministros de impresión",
  "Archivadores",
  "Papeles y sobres",
  "Seguridad industrial",
  "Herramientas",
  "Taladros",
  "Destornilladores",
  "Llaves inglesas",
  "Martillos",
  "Serruchos",
  "Sierras eléctricas",
  "Compresores",
  "Soldadoras",
  "Equipos de medición",
  "Ferretería",
  "Tornillos y tuercas",
  "Clavos",
  "Pinturas",
  "Rodillos y brochas",
  "Cintas adhesivas",
  "Lubricantes",
  "Automotriz",
  "Repuestos de autos",
  "Aceites y lubricantes",
  "Neumáticos",
  "Baterías",
  "Herramientas automotrices",
  "Tapizados",
  "Accesorios de autos",
  "Limpieza automotriz",
  "Seguridad vehicular",
  "Construcción",
  "Cemento",
  "Arena",
  "Ladrillos",
  "Hierros",
  "Maderas",
  "Tejas",
  "Azulejos",
  "Cerámicas",
  "Baños y grifería",
  "Pinturas para construcción",
  "Electricidad",
  "Cables eléctricos",
  "Enchufes",
  "Interruptores",
  "Luminarias",
  "Tableros eléctricos",
  "Baterías y pilas",
  "Energías renovables",
  "Paneles solares",
  "Inversores solares",
  "Baterías solares",
  "Iluminación LED",
  "Domótica",
  "Seguridad del hogar",
  "Cámaras de seguridad",
  "Alarmas",
  "Sensores de movimiento",
  "Videoporteros",
  "Cerraduras inteligentes",
  "Mascotas",
  "Comida para perros",
  "Comida para gatos",
  "Accesorios para mascotas",
  "Camas de mascotas",
  "Juguetes para mascotas",
  "Higiene de mascotas",
  "Acuarios",
  "Peces ornamentales",
  "Aves",
  "Reptiles",
  "Agricultura",
  "Semillas",
  "Fertilizantes",
  "Herramientas agrícolas",
  "Maquinaria agrícola",
  "Riego",
  "Insecticidas",
  "Ganadería",
  "Piensos",
  "Bebederos",
  "Medicinas veterinarias",
  "Ropa laboral",
  "Uniformes",
  "Botas de seguridad",
  "Guantes industriales",
  "Cascos de protección",
  "Chalecos reflectivos",
  "Seguridad eléctrica",
  "Material médico",
  "Muebles hospitalarios",
  "Instrumental quirúrgico",
  "Material descartable",
  "Transporte",
  "Accesorios de moto",
  "Repuestos de moto",
  "Bicicletas eléctricas",
  "Patinetes eléctricos",
  "Transporte marítimo",
  "Barcos y accesorios",
  "Arte y cultura",
  "Pinturas artísticas",
  "Lienzos",
  "Pinceles",
  "Escultura",
  "Artesanías",
  "Instrumentos musicales",
  "Guitarras",
  "Bajos",
  "Pianos",
  "Baterías musicales",
  "Micrófonos",
  "Equipos de sonido profesional",
  "Estudio de grabación",
  "Fotografía profesional",
  "Cine y video",
  "Iluminación profesional",
  "Vestimenta de espectáculo",
  "Cine en casa",
  "Streaming",
  "Suscripciones digitales",
  "Libros",
  "Revistas",
  "Cómics",
  "E-books",
  "Papelería artística",
  "Educación",
  "Cursos online",
  "Material educativo",
  "Software educativo",
  "Robótica",
  "Electrónica industrial",
  "Componentes electrónicos",
  "Sensores",
  "Microcontroladores",
  "Cables y conectores",
  "Automatización industrial",
  "PLC",
  "Controladores",
  "Instrumentación",
  "Laboratorio",
  "Químicos",
  "Equipos de laboratorio",
  "Vidriería de laboratorio",
  "Textil",
  "Tejidos",
  "Hilos y lanas",
  "Máquinas de coser",
  "Accesorios de costura",
  "Calzado artesanal",
  "Ropa ecológica",
  "Sustentabilidad",
  "Reciclaje",
  "Energía verde",
  "Transporte eléctrico",
  "Turismo",
  "Hoteles",
  "Pasajes aéreos",
  "Cruceros",
  "Tours guiados",
  "Seguros de viaje",
  "Gastronomía",
  "Alimentos",
  "Bebidas",
  "Vinos",
  "Cervezas artesanales",
  "Licores",
  "Frutas y verduras",
  "Carnes",
  "Embutidos",
  "Panadería",
  "Repostería",
  "Confitería",
  "Productos gourmet",
  "Comida orgánica",
  "Suplementos alimenticios",
  "Comida vegana",
  "Comida sin gluten",
  "Snacks saludables",
  "Congelados",
  "Lácteos",
  "Quesos",
  "Huevos",
  "Aceites y condimentos",
  "Salsas",
  "Pastas",
  "Cereales",
  "Legumbres",
  "Granos",
  "Bebidas sin alcohol",
  "Jugos",
  "Aguas minerales",
  "Bebidas energéticas",
  "Tés e infusiones",
  "Café",
  "Chocolates",
  "Golosinas",
  "Helados",
  "Catering",
  "Restauración",
  "Panaderías y confiterías",
  "Carnicerías",
  "Supermercados",
  "Tiendas naturistas",
  "Distribuidores de alimentos",
  "Tecnología verde",
  "Movilidad urbana",
  "Drones profesionales",
  "Impresión 3D",
  "Servicios en la nube",
  "Software empresarial",
  "Ciberseguridad",
  "Análisis de datos",
  "Desarrollo web",
  "Inteligencia artificial",
  "Realidad virtual",
  "Blockchain",
  "Finanzas",
  "Bancos",
  "Créditos",
  "Seguros",
  "Criptomonedas",
  "Inversiones",
  "Contabilidad",
  "Legal",
  "Servicios notariales",
  "Traducción",
  "Publicidad y marketing",
  "Diseño gráfico",
  "Fotografía comercial",
  "Consultoría",
  "Servicios profesionales",
  "Logística",
  "Transporte de carga",
  "Paquetería",
  "Almacenaje",
  "E-commerce",
  "Marketplaces",
  "Servicios digitales",
  "Streaming de música",
  "Streaming de video",
  "Aplicaciones móviles",
  "Gaming online",
  "NFTs",
  "Educación virtual",
  "Eventos y conferencias",
  "Cine y entretenimiento",
  "Música en vivo",
  "Festivales",
  "Producción audiovisual",
  "Diseño de interiores",
  "Arquitectura",
  "Urbanismo",
  "Decoración ecológica",
  "Paisajismo",
  "Bienestar",
  "Meditación",
  "Yoga",
  "Terapias alternativas",
  "Masajes",
  "Aromaterapia",
  "Espiritualidad",
  "Coaching",
  "Desarrollo personal",
  "Formación empresarial",
  "Coworking",
  "Espacios de oficina",
  "Emprendimiento",
  "Startups",
  "SaaS",
  "IoT",
  "Computación cuántica",
  "Robótica médica",
  "Agricultura inteligente",
  "Big Data",
  "Metaverso",
  "Turismo sostenible",
  "Agroindustria",
  "Moda sostenible",
  "Packaging ecológico",
  "Industria 4.0",
  "Fabricación aditiva",
  "Nanotecnología",
  "Bioingeniería",
  "Transporte autónomo",
  "Telemedicina",
  "Cuidado del adulto mayor",
  "Seguros médicos",
  "Servicios financieros digitales",
  "Créditos personales",
  "Fintech",
  "Inversiones sostenibles",
  "Arte digital",
  "Diseño UX/UI",
  "Producción musical",
  "Restauración de arte",
  "Cultura local",
  "Turismo rural",
  "Gastronomía regional",
  "Educación técnica",
  "Capacitación profesional",
  "Diseño de moda",
  "Estética capilar",
  "Reparación de dispositivos",
  "Repuestos electrónicos",
  "Servicios técnicos",
  "Mantenimiento industrial",
  "Sistemas de climatización",
  "Calefacción y refrigeración",
  "Fontanería",
  "Electricistas",
  "Carpintería",
  "Cerrajería",
  "Vidriería",
  "Pintura y decoración",
  "Mudanzas",
  "Servicios de limpieza",
  "Servicios para el hogar",
  "Fotografía social",
  "Eventos corporativos",
  "Organización de bodas",
  "Catering de eventos",
  "Decoración de fiestas",
  "Floristería",
  "Regalos empresariales",
  "Souvenirs",
  "Papelería personalizada",
  "Estampados",
  "Publicidad exterior",
  "Diseño publicitario",
  "Impresión digital",
  "Impresión offset",
  "Rotulación de vehículos",
  "Sublimación",
  "Merchandising",
  "Uniformes empresariales",
  "Identidad corporativa",
  "Community management",
  "Desarrollo de apps",
  "Analítica web",
  "Email marketing",
  "Publicidad digital",
  "SEO",
  "SEM",
  "Gestión de redes sociales",
  "Diseño de campañas publicitarias"
];

export const modes = {
  INS: "INS" /* Inserción */,
  UPD: "UPD" /* Actualización */,
  DLT: "DLT" /* Eliminación */,
  SUBSTR: "SUBSTR" /* Sustracción */
};
